[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2026.2.1"

components = [
    "apriltag",
    "cscore",
    "sim",
]

# Other pip packages to install
requires = [
     "robotpy-commands-v2==2026.2.1",
     "robotpy-rev==2026.0.1",
     "numpy",
     "robotpy-pathplannerlib==2026.1.1",
     #"photonlibpy==2026.0.1",
     "robotpy-urcl==2026.0.0.1",
     "pyfrc==2026.0.1",
     "protobuf==6.33.1",
     "black==25.12.0; platform_machine != 'roborio'",
     "coverage==7.4.1; platform_machine != 'roborio'",
     "ast-selector==0.2.0; platform_machine != 'roborio'",
     "asttokens==2.4.1; platform_machine != 'roborio'",
     "pytest-timeout==2.4.0; platform_machine != 'roborio'",
     "pynetconsole==2.0.4; platform_machine != 'roborio'",
     "grpcio-tools==1.76.0; platform_machine != 'roborio'",
     #"sleipnirgroup-choreolib==2025.0.3",
]

[tool.coverage.html]
directory = "coverage_html_report"

[tool.coverage.run]
branch = true
relative_files = true
